# Please ensure your container has the necessary resources allocated to it. We recommend 2GiB of memory allocated to accommodate both the application server and the git processes.
#
version: '2'

services:
  bitbucket:
    container_name: bitbucket
    image: atlassian/bitbucket-server:7.7.0
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - $PWD/data/bitbucket:/var/atlassian/application-data/bitbucket
    - $PWD/data/bitbucket-shared:/var/atlassian/application-data/bitbucket/shared 
    environment:
    - TZ=Asia/Taipei
#    network_mode:  "host"
    ports: 
     - "7990:7990"
     - "7999:7999" 
 
